### ISSUE TITLE
Empty webserver type

### ISSUE THREAD

**Issue by edermi** [hartmond/certbutler#5]
It should be possible to issue certificates without webserver interaction afterwards.
Probably the easiest solution is to return a dummy Interaction that simply does nothing here:
https://github.com/hartmond/certbutler/blob/master/webserver/webserver.go#L31

**Comment by hartmond** [comment]
This would not work as the interaction defines the certificate file format and also does the file writing.
Adding a interaction would duplicate the nginx interaction almost completely.
I would prefer to have a "updateServer" config bool which skips the updateServer call in https://github.com/hartmond/certbutler/blob/master/scheduler/scheduler.go#L87

**Comment by edermi** [comment]
I only took a quick look at it. I'm fine with having an updateServer config. For me it is important to have the ability to just issue certificates without any further system interaction. It still feels a bit weird to have the "nginx" mode despite not using nginx, just issuing a certificate. Maybe we should rethink the naming?

**Comment by hartmond** [comment]
It ist still the nginx file format (cert and key in different files compared to the one file for haproxy). So it is a certificate for nginx without updating the server. I think it is most simple this way. The only alternative I can think of to clarify the naming is to split up cert format and deployment type and have deployments depend on a specific format which would create a lot of additional complexity (especially to include the OCSP updates for haproxy). But I am open for ideas.

**Comment by edermi** [comment]
I wouldn't call it 'nginx file format' - PEM is pretty common standard ;)
For me, it is clear, but the naming and implicit behavior might be confusing to other users. Maybe splitting certificate format and actual deployment is not a bad idea. Another idea is to have a "raw" / "empty" / "none" deployment that allows to specify via parameters how to export the certificate.

**Comment by hartmond** [comment]
They are both PEM. But once in one pem file and once in two pem files. 
But I see the point with the implicit behaivour, a single unintuitive but well documented switch is better than implicit effects. I restructured the configuration and program flow to split file format and deployment.
Side effect: it now covers even more scenarios (e.g. nginx with prepared ocsp responses).
It's on the develop branch. Maybe you have time to take a look at it.

**Comment by edermi** [comment]
Your changes look fine to me. I had to fix a small bug for reloading nginx but now it works on my server. I'm fine with merging to master. Once I find some spare time I will deploy the latest version to a few more systems.
